core_beefNoodles/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using core_beefNoodles.Models;

namespace core_beefNoodles.ViewModels
{
    public class HomeViewModel
    {
        public IList<Noodle> noodles { get; set; }
        public IList<Feedback> feedbacks { get; set; }
    }
}

core_beefNoodles/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using core_beefNoodles.Models;
using Microsoft.AspNetCore.Mvc;

namespace core_beefNoodles.Controllers
{
    public class FeedbackController : Controller
    {
        private IFeedbackRepositroy _feedbackRepositroy;

        public FeedbackController(IFeedbackRepositroy feedbackRepositroy)
        {
            _feedbackRepositroy = feedbackRepositroy;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                feedback.CreateDataUTC = DateTime.Now;
                _feedbackRepositroy.AddFeedback(feedback);
                return RedirectToAction("FeedbackComplete");
            }
            return View();
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }

    }
}

core_beefNoodles/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using core_beefNoodles.Models;
using core_beefNoodles.ViewModels;

namespace core_beefNoodles.Controllers
{
    //[Route("[controller]/[action]")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private INoodleRepository _noodleRepository;
        private IFeedbackRepositroy _FeedbackRepositroy;

        public HomeController(ILogger<HomeController> logger,INoodleRepository noodleRepository, IFeedbackRepositroy FeedbackRepositroy)
        {
            _logger = logger;
            _noodleRepository = noodleRepository;
            _FeedbackRepositroy = FeedbackRepositroy;
        }

        public IActionResult Index()
        {
            var viewModel = new HomeViewModel
            {
                noodles = _noodleRepository.GetAllNoodles().ToList(),
                feedbacks = _FeedbackRepositroy.GetAllFeedbacks().ToList()
            };
            return View(viewModel);
        }

        public string About()
        {
            return "Hello from About";
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Detail(int id)
        {
            return View(_noodleRepository.GetNoodleById(id));
        }
    }
}

core_beefNoodles/Views/Home/Detail.cshtml
@model Noodle


    <nav class="nav nav-pills nav-fill">
        <a class="nav-item nav-link" a asp-controller="Home" asp-action="Index">首页</a>
        <a class="nav-item nav-link" asp-controller="Feedback" asp-action="Index">意见反馈</a>
        <a class="nav-item nav-link active">详情</a>
    </nav>

<div style="width:100%;">
    <h1>@Model.Name</h1>
</div>

<div class="img-thumbnail" style="width:100%">
    <div style="text-align:center;">
        <img class="img-thumbnail" src="@Model.ImageUrl" style="width:80%;height:auto;" />
    </div>  
    <div class="figure-caption" style="padding-left:15%;padding-right:15%;">
        <h3 class="float-right">$ @Model.Price</h3>
        <h3>
            @Model.Name
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDexcription</p>
    </div>
</div>

core_beefNoodles/Views/Home/Index.cshtml
@*@model IEnumerable<core_beefNoodles.Models.Noodle>*@
@model core_beefNoodles.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@

<nav class="nav nav-pills nav-fill">
    <a class="nav-item nav-link active" a asp-controller="Home" asp-action="Index">首页</a>
    <a class="nav-item nav-link" asp-controller="Feedback" asp-action="Index">意见反馈</a>
</nav>

<div style="width:100%;">
    <h2>产品列表</h2>
</div>


@foreach (var noodle in Model.noodles)
{
<div class="col-sm-8 col-lg-3 col-md-6" style="margin-bottom:25px;">
    <a href="Home/Detail?id=@noodle.Id">
        <div class="img-thumbnail">
            <img style="width:100%;height:300px;" src="@noodle.ImageUrl" />
            <div class="figure-caption">
                <h3>$ @noodle.Price</h3>
                <h3>
                    @noodle.Name
                </h3>
                <p>@noodle.ShortDescription</p>
            </div>
        </div>
    </a>
</div>

}
<div style="width:100%;">
    <h2>评论</h2>
</div>

<div class="list-group" style="width:100%">

    @foreach (var feedback in Model.feedbacks)
    {
        <a class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="form-control-plaintext">@feedback.Name</h5>
                <small class="float-right">@feedback.CreateDataUTC</small>
            </div>
            <p>@feedback.Message</p>
        </a>
    }
</div>